version: '3'

services:
  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - default
  api:
    image: node:11-alpine
    working_dir: /var/www/html
    depends_on:
      - db
    links:
      - db
    user: ${UID}:${GID}
    ports:
      - 3000:3000
      - 9000:9000
    volumes:
      - .:/var/www/html
      - /var/www/html/node_modules
      - /var/www/html/libeo/node_modules
      - /var/www/html/libeoweb/node_modules
      - .env:/var/www/html/.env
      - .env:/var/www/html/libeo/.env
    command: sh -c  "apk add --no-cache git && yarn workspaces run install; yarn workspace libeo run dev & yarn workspace libeoweb run start"
    labels:
      - 'traefik.enable=true'
      - 'traefik.api.frontend.rule=Host:api.${DOMAIN}'
      - 'traefik.api.port=9000'
      - 'traefik.web.frontend.rule=Host:app.${DOMAIN}'
      - 'traefik.web.port=3000'
  # Workaround to not launch apache server
  # web:
  #   image: alpine:latest
  #   command: 'true'
  #   entrypoint: 'true'

volumes:
  db-data:
